services:
  - type: web
    name: donghanhso-backend
    env: node
    plan: free
    buildCommand: npm --prefix backend install && npm --prefix backend run build
    startCommand: npm --prefix backend run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        sync: false
